### ISSUE TITLE
Falta etiqueta Label de ejercicio de accesibilidad

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/ejercicios2024-franco2355#1]
https://github.com/UCC-LabCompu2/ejercicios2024-franco2355/blob/cd42be9cda2a95946f40b5e4c08bc63282659b40/Ejercicios-HTML/ej_formulario.html#L54

**Comment by franco2355** [comment]
Se coloco la etiqueta Label sobre el ej_formulario.html
