### ISSUE TITLE
Debe emplearse imagen pre-existente de  la carpeta "imagenes"

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/ejercicios2024-franco2355#2]
https://github.com/UCC-LabCompu2/ejercicios2024-franco2355/blob/cd42be9cda2a95946f40b5e4c08bc63282659b40/Ejercicios-HTML/ej_listas.html#L24

**Comment by franco2355** [comment]
Se utilizo la foto que se encuentra en la carpeta imágenes para realizar el proyecto además se dejo mas legible
