### ISSUE TITLE
Falta ejercicio de U6: Responsive

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/ejercicios2024-franco2355#5]
https://github.com/UCC-LabCompu2/ejercicios2024-franco2355/blob/cd42be9cda2a95946f40b5e4c08bc63282659b40/Ejercicios-CSS/ej_instagram.html#L9

Ver el siguiente video de la unidad 6:
https://ucc-labcompu2.github.io/filminas/U6_responsive.html#/22

**Comment by franco2355** [comment]
Se implemento el ej_Instagram.html
